name: build

on:
  - push
  - pull_request

jobs:

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Remove stray python binary symlinks
        run: |
          find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete -print
          brew unlink python && brew link --overwrite python

      - name: Install deps
        run: |
          brew update
          brew install automake autoconf libtool pkg-config coreutils gnu-sed wget meson ninja
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: Download deps
        run: |
          cd buildscripts
          mkdir -p sdk && ln -s "$ANDROID_HOME" sdk/android-sdk-mac
          TRAVIS=1 ./download.sh

      - name: Build
        run: |
          cd buildscripts && ./buildall.sh
          
      - name: relocate apks
        run: |
          mkdir -p app/build/outputs/apk/release
          cp ./app/build/outputs/apk/api29/debug/app-api29-armeabi-v7a-debug.apk
          cp ./app/build/outputs/apk/api29/debug/app-api29-universal-debug.apk
          cp ./app/build/outputs/apk/api29/release/app-api29-armeabi-v7a-release-unsigned.apk
          cp ./app/build/outputs/apk/api29/release/app-api29-universal-release-unsigned.apk
          cp ./app/build/outputs/apk/default/debug/app-default-armeabi-v7a-debug.apk
          cp ./app/build/outputs/apk/default/debug/app-default-universal-debug.apk
          cp ./app/build/outputs/apk/default/release/app-default-armeabi-v7a-release-unsigned.apk
          cp ./app/build/outputs/apk/default/release/app-default-universal-release-unsigned.apk
          
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        #  keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name : upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: Vanilla-Build
          path: |
            app/build/outputs/apk/api29/debug/app-api29-armeabi-v7a-debug.apk
            app/build/outputs/apk/api29/debug/app-api29-universal-debug.apk
            app/build/outputs/apk/api29/release/app-api29-armeabi-v7a-release-unsigned.apk
            app/build/outputs/apk/api29/release/app-api29-universal-release-unsigned.apk
            app/build/outputs/apk/default/debug/app-default-armeabi-v7a-debug.apk
            app/build/outputs/apk/default/debug/app-default-universal-debug.apk
            app/build/outputs/apk/default/release/app-default-armeabi-v7a-release-unsigned.apk
            app/build/outputs/apk/default/release/app-default-universal-release-unsigned.apk
